server:
  servlet:
    context-path: /cas
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.3.85
logging:
  level:
    com.unicom.smartcity: debug

system:
  login-url: /login
  logout-url: /logout