server:
  servlet:
    context-path: /cas
spring:
  thymeleaf:
    cache: false
logging:
  level:
    web: debug
    com.unicom.smartcity: debug

system:
  login-url: /login
  logout-url: /logout
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:8080/.well-known/jwks.json
