server:
  servlet:
    context-path: /cas
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cas_server?createDatabaseIfNotExist=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  thymeleaf:
    cache: false
  redis:
    host: 192.168.3.85
logging:
  level:
    com.unicom.smartcity: debug